version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: perpdex-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: perpdex
      MYSQL_USER: perpdex
      MYSQL_PASSWORD: perpdex
      MYSQL_ROOT_PASSWORD: perpdexroot
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - perpdex-mysql:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: perpdex-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  perpdex-mysql:
